steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ankieta-logopedyczna-cloud-run/ankieta-backend', '.']

images:
  - 'gcr.io/ankieta-logopedyczna-cloud-run/ankieta-backend'

options:
  logging: CLOUD_LOGGING_ONLY
